name: sitecast
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - streamlit=1.28.0
  - pandas=2.0.3
  - numpy=1.24.3
  - openpyxl=3.1.2
  - matplotlib=3.7.2
  - scikit-learn=1.3.0
  - pip
  - pip:
    - ifcopenshell==0.7.0